repos:
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      stages: [commit]
      exclude: ^scripts/
# -   repo: local
#     hooks:
#     - id: pytest
#       name: pytest
#       language: system
#       entry: pytest
#       pass_filenames: false
#       always_run: true
#       stages: [commit]